#!/usr/bin/expect -f

set timeout -1

cd /Users/admin/Development/signs-app/signs-mobile

spawn eas build --profile production --platform ios

expect {
    "Do you want to log in to your Apple account?" {
        send "n\r"
        exp_continue
    }
    "Distribution Certificate is valid" {
        exp_continue
    }
    "All credentials are ready to build" {
        exp_continue
    }
    eof
}
