// This file is generated by scripts/generatePlatformIcons.js
// Do not edit by hand — re-run the generator if you add/remove assets.

const PLATFORM_ICONS: { [key: string]: any } = {
  'checkatrade': require('../assets/platform-logos/checkatrade.png'),
  'facebook': require('../assets/platform-logos/facebook.png'),
  'google': require('../assets/platform-logos/google.png'),
  'instagram': require('../assets/platform-logos/instagram.png'),
  'linkedin': require('../assets/platform-logos/linkedin.png'),
  'ratedpeople': require('../assets/platform-logos/ratedpeople.png'),
  'tiktok': require('../assets/platform-logos/tiktok.png'),
  'tripadvisor': require('../assets/platform-logos/tripadvisor.png'),
  'trustatrader': require('../assets/platform-logos/trustatrader.png'),
  'trustpilot': require('../assets/platform-logos/trustpilot.png'),
  'twitter': require('../assets/platform-logos/twitter.png'),
  'yell': require('../assets/platform-logos/yell.png'),
  'yelp': require('../assets/platform-logos/yelp.png')
};

export default PLATFORM_ICONS;
