import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { generateInvoicePDF } from '@/lib/invoiceGenerator';
// Outbound email will be sent via Resend API

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { customerName, customerEmail, items } = body;

    if (!customerName || !customerEmail || !items || items.length === 0) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(customerEmail)) {
      return NextResponse.json(
        { error: 'Invalid email address' },
        { status: 400 }
      );
    }

    // Calculate totals
      const invoiceItems = items.map((item: any) => ({
        productId: item.productId || 'custom-item',
        productName: item.productName || item.name || 'Custom Item',
        quantity: Number(item.quantity ?? 1),
        unitPrice: Number(item.unitPrice ?? 0),
        totalPrice: Number(item.quantity ?? 1) * Number(item.unitPrice ?? 0),
      }));

    const totalAmount = invoiceItems.reduce((sum: number, item: any) => sum + item.totalPrice, 0);

    // Create invoice in database with tracking token
    const invoice = await prisma.invoice.create({
      data: {
        invoiceNumber: `INV-${Date.now()}`, // Simple ID generation
        customerEmail,
        customerName,
        totalAmount,
        status: 'pending',
        trackingToken: undefined, // Will be auto-generated by default
        items: {
          create: invoiceItems,
        },
      },
      include: {
        items: true,
      },
    });

    // Generate PDF
    // Map prisma items to the format expected by generateInvoicePDF
    const pdfItems = invoice.items.map(item => ({
      name: item.productName,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      totalPrice: item.totalPrice
    }));

    const pdfBuffer = await generateInvoicePDF({
      invoiceNumber: invoice.invoiceNumber,
      customerName: invoice.customerName,
      items: pdfItems,
      totalAmount: invoice.totalAmount,
      createdAt: invoice.createdAt,
      showPaidStamp: false // Default to false for new invoices
    });

    // Send email via Resend - don't fail request if it errors
    try {
      const apiKey = process.env.RESEND_API_KEY;
      if (!apiKey) {
        throw new Error('RESEND_API_KEY not set');
      }

      const from = process.env.EMAIL_FROM || 'invoices@review-signs.co.uk';
      const html = `
          <h2>Hello ${customerName},</h2>
          <p>Please find your invoice attached.</p>
          <p><strong>Invoice Number:</strong> ${invoice.invoiceNumber}</p>
          <p><strong>Total Amount:</strong> £${totalAmount.toFixed(2)}</p>
          <h3>Items:</h3>
          <ul>
            ${invoiceItems.map((item: any) => `<li>${item.productName}: ${item.quantity} × £${item.unitPrice.toFixed(2)} = £${item.totalPrice.toFixed(2)}</li>`).join('')}
          </ul>
          <p>Thank you for your business!</p>
          <p>Best regards,<br/><strong>Review Signs Team</strong></p>
        `;

      const attachment = {
        filename: `${invoice.invoiceNumber}.pdf`,
        content: pdfBuffer.toString('base64'),
      };

      const resp = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from,
          to: customerEmail,
          subject: `Invoice ${invoice.invoiceNumber} - Review Signs`,
          html,
          attachments: [attachment],
        }),
      });

      if (!resp.ok) {
        const text = await resp.text();
        console.error('Resend email send failed:', resp.status, text);
      } else {
        await prisma.invoice.update({
          where: { id: invoice.id },
          data: { status: 'sent', sentAt: new Date() },
        });
      }
    } catch (emailError) {
      console.error('Failed to send invoice email (Resend), but invoice was created:', emailError);
      // Don't fail the entire request if email fails
    }

    return NextResponse.json({ 
      success: true, 
      invoice,
      message: 'Invoice created successfully'
    });
  } catch (error: any) {
    console.error('Error creating invoice:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create invoice' },
      { status: 500 }
    );
  }
}
