import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      businessId,
      placeId,
      promotionId,
      winnerCode, // Usually generated by client or server. Mobile generates it?
      prizeType,
      prizeName,
      prizeAmount,
      isWin,
      gameType
    } = body;

    if (!promotionId || !businessId) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Check if promotion exists in FruitMachinePromotion
    // If it's a legacy Promotion, we might not be able to link it with FK
    // So we check first.
    const fmPromotion = await prisma.fruitMachinePromotion.findUnique({
      where: { id: promotionId }
    });

    if (fmPromotion) {
      // It's a new promotion, save with relation
      const result = await prisma.fruitMachineResult.create({
        data: {
          businessId,
          placeId,
          promotionId,
          winnerCode: winnerCode || `spin-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
          prizeType: prizeType || 'gift',
          prizeName: prizeName || 'Unknown',
          prizeValue: prizeAmount ? String(prizeAmount) : null,
          isWin: isWin || false,
        }
      });
      return NextResponse.json({ success: true, result });
    } else {
      // Legacy Promotion or invalid ID
      // We can't save to FruitMachineResult because of FK constraint
      // We could log it or just ignore it for now.
      // Or we could try to find the legacy promotion
      const legacyPromotion = await prisma.promotion.findUnique({
        where: { id: promotionId }
      });

      if (legacyPromotion) {
        console.log('Legacy promotion spin recorded (not saved to DB):', body);
        return NextResponse.json({ success: true, message: 'Legacy spin acknowledged' });
      }

      return NextResponse.json(
        { error: 'Promotion not found' },
        { status: 404 }
      );
    }

  } catch (error) {
    console.error('Error recording spin:', error);
    return NextResponse.json(
      { error: 'Failed to record spin' },
      { status: 500 }
    );
  }
}
