const fs = require('fs');
const path = require('path');

const logosDir = path.join(__dirname, '..', 'assets', 'platform-logos');
const outFile = path.join(__dirname, '..', 'assets', 'platform-icons.ts');

if (!fs.existsSync(logosDir)) {
  console.error('platform-logos directory not found at', logosDir);
  process.exit(1);
}

const files = fs.readdirSync(logosDir).filter(f => /\.(png|jpg|jpeg|webp|gif)$/.test(f));

const entries = files.map(f => {
  const key = path.basename(f, path.extname(f)).toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const rel = `../assets/platform-logos/${f}`;
  return `  '${key}': require('${rel}')`;
});

const content = `// This file is generated by scripts/generatePlatformIcons.js
// Do not edit by hand — re-run the generator if you add/remove assets.

const PLATFORM_ICONS: { [key: string]: any } = {
${entries.join(',\n')}
};

export default PLATFORM_ICONS;
`;

fs.writeFileSync(outFile, content, 'utf8');
console.log('Wrote', outFile, 'with', files.length, 'icons');
